# -----------------------------------------------------------------------------
# Site Settings
# -----------------------------------------------------------------------------

name: Lei Xiong
email: jsxlei@gmail.com

# footer_text: >
#   Powered by <a href="http://jekyllrb.com/" target="_blank">Jekyll</a> with <a href="https://github.com/alshedivat/al-folio">al-folio</a> theme.
#   Hosted by <a href="https://pages.github.com/" target="_blank">GitHub Pages</a>.
# last_updated: true

url:  # the base hostname & protocol for your site
baseurl:  # the subpath of your site, e.g. /blog/

# -----------------------------------------------------------------------------
# Social Integration
# -----------------------------------------------------------------------------
scholar_userid: ky6bUTgAAAAJ&hl
github_username: jsxlei
orcid_id: http://orcid.org/0000-0002-2392-114X
linkedin_username: 
facebook_username: jsxlei
twitter_username: jsxlei
contact_note: Feel free to drop me a line via e-mail.


#google_analytics: UA-54519238-1

# -----------------------------------------------------------------------------
# Blog
# -----------------------------------------------------------------------------
# blog_name: al-folio
# blog_description: a simple whitespace theme for academics

# # Pagination
# paginate: 4
# permalink: /blog/:year/:title/
# paginate_path: /blog/page:num/

# text:
#   pagination:
#     newer: 'Newer'
#     older: 'Older'

# # Comments
# disqus_shortname: al-folio # put your disqus shortname

# # Optional features
# show_social_icons:  false
# enable_anchorjs:    false
# enable_katex:       true

# -----------------------------------------------------------------------------
# Collections
# -----------------------------------------------------------------------------
collections:
  news:
    defaults:
      layout: page
    output: true
    permalink: /news/:path/
  projects:
    output: true
    permalink: /projects/:path/

news_limit: 10

# -----------------------------------------------------------------------------
# Jekyll Settings
# -----------------------------------------------------------------------------

# Build settings
markdown: kramdown
# highlighter: pygments

# Includes
include: ['_pages']

# Plugins
plugins:
  - jekyll-paginate
  - jekyll/scholar
  - jemoji

# Jekyll-Scholar
scholar:
  last_name: Xiong
  style: apa
  locale: en
  sort_by: year
  order: descending
  source: /_bibliography/
  bibliography: papers.bib
  bibliography_template: publication
  reference_tagname: div

  replace_strings: true
  join_strings: true

  details_dir: bibliography
  details_layout: bibtex.html
  details_link: Details

  query: "@*"

# -----------------------------------------------------------------------------
# Other settings
# -----------------------------------------------------------------------------
jquery_version: "1.12.4"
katex_version: "0.7.1"
anchorjs_version: "3.2.2"
